language: bash
services: docker

install:
  - git clone https://github.com/samejack/docker-mysql

before_script:
  - image="samejack/mysql"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images
